# Generated by Django 2.2.5 on 2019-09-22 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='State')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('deleted', models.DateTimeField(auto_now=True, verbose_name='Deleted')),
                ('story', models.TextField(verbose_name='Story')),
                ('mision', models.TextField(verbose_name='Mision')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('direccion', models.CharField(max_length=50, verbose_name='Direction')),
                ('phone', models.CharField(max_length=50, verbose_name='Phone')),
                ('facebook', models.URLField(verbose_name='Facebook')),
                ('twitter', models.URLField(verbose_name='Twitter')),
                ('instagram', models.URLField(verbose_name='Instagram')),
                ('youtube', models.URLField(verbose_name='Youtube')),
                ('gituhb', models.URLField(verbose_name='Github')),
            ],
            options={
                'verbose_name': 'About',
            },
        ),
    ]
