# Generated by Django 2.2.5 on 2019-09-22 09:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='mision',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
