# Generated by Django 2.2.5 on 2019-09-22 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_auto_20190922_0906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='direccion',
            new_name='address',
        ),
        migrations.AlterField(
            model_name='about',
            name='mision',
            field=models.TextField(verbose_name='Mision'),
        ),
    ]
