# Generated by Django 2.2.5 on 2019-09-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_auto_20190922_0951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='gituhb',
            new_name='github',
        ),
        migrations.AlterField(
            model_name='about',
            name='address',
            field=models.CharField(max_length=50, verbose_name='Address'),
        ),
    ]
