# Generated by Django 2.2.5 on 2019-09-23 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190922_0436'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
