# Generated by Django 2.2.5 on 2019-09-24 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190923_0646'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='State')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('deleted', models.DateTimeField(auto_now=True, verbose_name='Deleted')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('slug', models.CharField(max_length=100, verbose_name='Slug')),
                ('description', models.CharField(max_length=150, verbose_name='Description')),
                ('imagen', models.URLField(verbose_name='Imagen')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Author')),
                ('category', models.ManyToManyField(to='blog.Category')),
            ],
            options={
                'verbose_name': 'Post',
            },
        ),
    ]
