# Generated by Django 2.2.5 on 2019-09-28 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190924_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='post_category/', verbose_name='Image'),
        ),
    ]
