# Generated by Django 2.2.5 on 2019-09-28 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='State')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('deleted', models.DateTimeField(auto_now=True, verbose_name='Deleted')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.CharField(max_length=250, verbose_name='Description')),
                ('image', models.ImageField(upload_to=None, verbose_name='Product_Image/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Price')),
                ('stock', models.SmallIntegerField(verbose_name='Stock')),
            ],
            options={
                'verbose_name': 'Product',
            },
        ),
    ]
