# Generated by Django 2.2.5 on 2019-09-28 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20190928_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='sex',
            name='image',
            field=models.ImageField(default=1, max_length=250, upload_to='sex_product', verbose_name='Image'),
            preserve_default=False,
        ),
    ]
