# Generated by Django 2.2.5 on 2019-09-29 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_sex_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='promotion',
            field=models.BooleanField(default=False, verbose_name='Promotion'),
        ),
    ]
